compressionLevel: mixed

yarnPath: .yarn/releases/yarn-4.8.1.cjs

# pnp breaks rider :( 
# see https://youtrack.jetbrains.com/issue/RIDER-113065
nodeLinker: node-modules

logFilters:
  - code: YN0002 # false "unmet peer dependency" error
    level: discard
